name: Coverage Report
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage-report:
    name: Generates and publishes coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Generate coverage report
        run: make coverage.out
      - name: Publishes report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
          language: go
          force-coverage-parser: go
