name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-go-tess:
    name: Run Go Tests
    strategy:
      matrix:
        go-version: [ '1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19' ]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
          check-latest: true
      - name: Prints Go version
        run: go version
      - name: Run Tests
        run: make test

  coverage-report:
    name: Generates and publishes coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Generate coverage report
        run: make coverage
      - name: Publishes report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
          language: go
          force-coverage-parser: go
